# Generated by Django 2.0 on 2019-07-23 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='blog',
            new_name='BlogsPost',
        ),
    ]
